Elcom/Controllers/NextController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using Elcom.Models;
using Microsoft.AspNetCore.Mvc;

namespace Elcom.Controllers
{
    public class NextController : Controller
    {
        public ActionResult XlsxOrPartial(Action action, int partial, Param parameter = null)
        {
            if (partial == 0)
                return Helper.GetXlsxFile(action, parameter is null ? null : new Param[] { parameter });
            else
                return PartialView("_TargetTable", Helper.GetDataTable(action, parameter is null ? null : new Param[] { parameter }));
        }
        
        public ActionResult XlsxOrPartial(Action action, int partial, Param[] parameters)
        {
            if (partial == 0)
                return Helper.GetXlsxFile(action, parameters);
            else
                return PartialView("_TargetTable", Helper.GetDataTable(action, parameters));
        }

        public IActionResult Main()
        {
            ViewData["Title"] = "Главное меню";
            var command = new FunctionCommand("table(pkg_cmacros.getSheets)", new Param[] { new Param("accesslevel", User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value) });
            var caller = new DbCaller(command);
            caller.DoWork();
            if (((DataTable)caller.GetResult()).Rows.Count == 0)
            {
                ViewBag.Message = "Данному пользователю недоступны какие-либо действия!";
                return RedirectToAction("Login", "Home");
            }

            List<string> availableSheetsName = new List<string>();
            foreach (DataRow row in ((DataTable) caller.GetResult()).Rows)
            {
                availableSheetsName.Add(row[0].ToString());
            }

            List<Sheet> availableSheets =
                (List<Sheet>) Options.Sheets.Where(sheet => availableSheetsName.Contains(sheet.Name));
            return View("Main", availableSheets);
        }
        
        public ActionResult GetCommonSheet(string sheet, int action, int partial = 0)
        {
            var CurrentAction = Options.Sheets[sheet][action];
            List<Param> paramList = new List<Param>();
            foreach (var param in CurrentAction.parameters) //Request.Form
            {
                paramList.Add(new Param(param.Description, Request.Form[param.Name]));
            };
            return XlsxOrPartial(CurrentAction, partial, paramList.ToArray());
        }

        public ActionResult XlsxOrPartial(string sheetName, int partial, Param[] parameters)
        {
            if (partial == 0)
                return Helper.GetXlsxFile(sheetName, parameters);
            else
                return PartialView("_TargetTable", Helper.GetDataTable(sheetName, parameters));

            //return Content(Convert.ToBase64String(Helper.GetBytesArray("Purchaser", sheetName, parameters)));
        }

        [HttpGet]
        public ActionResult ShowPartialForm(string viewName)
        {
            return PartialView(viewName);
        }
    }
}

Elcom/Views/Next/Main.cshtml
@using Action = Elcom.Models.Action
@using Sheet = Elcom.Models.Sheet
@using Param = Elcom.Models.Param
@model List<Sheet>
<div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col workingSubject">
                            <h6>Выберите лист:</h6>
                        </div>
                    </div>
                    <div class="workingFieldLittle">
                        @foreach (Sheet sheet in @Model)
                        {
                        <div class="row">
                            <div class="col">
                                <a class="subject" href="#" onclick="ShowSheet('@sheet.Name');">@sheet.Description</a>
                            </div>
                        </div>
                        }
                    </div>
                    <div class="row">
                        <div class="col workingSubject" id="caption">
                            <h6>Выберите действие:</h6>
                        </div>
                    </div>
                    <div class="workingFieldLittle">
                        @foreach (Sheet sheet in @Model)
                            {
                            <div id="@sheet.Name" class="Sheets" style="display:none">@Html.Partial("_" + @sheet[3])
                                @foreach (Action action in sheet.Actions)
                                {
                                    @using (Html.BeginForm("GetCommonSheet", "Next", FormMethod.Post))
                                    {
                                        <input name="sheet" type="hidden" value="@sheet.Name"/>
                                        <input name="action" type="hidden" value="@action.Id"/>
                                        @foreach (Param param in action.parameters)
                                        {
                                            @Html.Partial("_Input", param)
                                        }
                                        @Html.Partial("_PartialOrExcelSubmit", action)
                                    }
                                }
                            </div>
                            }
                    </div>
                </div>
            </div>
            <div class="col-10">
                <div class="container-fluid">
                    <div class="row">
                        <div id="TargetTable" class="col workingField" style="display: block;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="LoadingModal" class="modal" tabindex="-1" role="dialog" display="none">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Происходит загрузка данных</h4>
                    </div>
                    <div class="modal-body">
                        Пожалуйста, подождите
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
    var CurrentSheet = "Dates";
    function ShowSheet(sheetName) {
        try {
            document.getElementById(CurrentSheet).style.display = "none";
        }
        catch (e) {
        }
        document.getElementById(sheetName).style.display = "block";
        CurrentSheet = sheetName;
        }
</script>