Elcom/Models/Statics/Sheets.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Elcom.Models
{
    public class SheetList : IEnumerable<Sheet>
    {
        private List<Sheet> _sheetList = new List<Sheet>();

        public Sheet this[int index] => _sheetList[index];

        public Sheet this[string name] => _sheetList.FirstOrDefault(x => x.Name.Equals(name)) ?? _sheetList.FirstOrDefault(x => x.Description == name);

        public Sheet this[string description, string accessLevel] => _sheetList.Where(x => x.Description == description).FirstOrDefault(x => x.AccessLevel == accessLevel);


        public IEnumerator<Sheet> GetEnumerator()
        {
            return _sheetList.GetEnumerator();
        }

        public void Update()
        {
            // Получаем результирующий набор всех листов по доступам
            //TODO Ввести актуальный запрос
            var command = new TextCommand(@"SELECT Description, Remark1, Remark2, Remark3 FROM elco.THEOPTION WHERE OPTIONLISTNUMBER = 'CMACROS'", Returns.Table);
            var caller = new DbCaller(command);
            DataTable table = (DataTable)caller.DoWork();

            foreach (DataRow row in table.Rows)
            {
                // Создаем лист 
                var sheet = new Sheet(row[0].ToString(), row[1].ToString(), row[2].ToString(), row[3].ToString());
                //Выгружаем экшены для этого листа
                //TODO Ввести актуальный запрос
                var actionsCommand = new TextCommand(@"SELECT Description, Remark1, Remark2, Remark3 FROM elco.THEOPTION WHERE OPTIONLISTNUMBER = 'CMACROS'", Returns.Table);
                var actionsCaller = new DbCaller(actionsCommand);
                DataTable actionsTable = (DataTable)actionsCaller.DoWork();
                foreach (DataRow actionRow in actionsTable.Rows)
                {
                    var action = new Action(actionRow[1].ToString(), int.Parse(actionRow[2].ToString()), actionRow[2].ToString(), actionRow[3].ToString());
                    //Выгружаем параметры для этого экшена
                    //TODO Ввести актуальный запрос
                    var paramsCommand = new TextCommand(@"SELECT Description, Remark1, Remark2, Remark3 FROM elco.THEOPTION WHERE OPTIONLISTNUMBER = 'CMACROS'", Returns.Table);
                    var paramsCaller = new DbCaller(paramsCommand);
                    DataTable paramsTable = (DataTable)paramsCaller.DoWork();
                    foreach (DataRow paramRow in paramsTable.Rows)
                    {
                        action.parameters.Add(new Param(paramRow[1].ToString(), paramRow[2].ToString(), int.Parse(paramRow[3].ToString()), paramRow[4].ToString(), paramRow[5].ToString()));
                    }
                    sheet.Actions.Add(action);
                }
                //Добавляем в общий список листов готовый лист с экшенами и параметрами
                _sheetList.Add(sheet);
            }
        } 

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _sheetList.GetEnumerator();
        }
    }

    /// <summary>
    /// Класс должности. Хранит в себе название и список листов, которые ему доступны
    /// </summary>
    public class Employee
    {
        // Должность
        public string Position;
        // Список листов
        public List<Sheet> Sheets = new List<Sheet>();
        // Конструктор с должностью из перечисления
        public Employee(string position)
        {
            Position = position;
        }
        // Конструктор с названием должности из перечисления
        /*
        public Employee(string position)
        {
            // Насильно приводим строку позиции к виду перечисления и заносим в позицию
            Position = (Position)System.Enum.Parse(typeof(Position), position);
        }
        */
        /// <summary>
        /// Заносит список листов в должность
        /// </summary>
        public void SetSheets(List<Sheet> sheets)
        {
            Sheets = sheets;
        }

        /// <summary>
        /// Возвращает лист с указанным названием
        /// </summary>
        /// <param name="sheetName">Название искомого листа</param>
        public Sheet GetSheet(string sheetName)
        {
            var search = Sheets.FirstOrDefault(x => x.Description.Equals(sheetName));
            return search ?? Sheets.FirstOrDefault(x => x.Name.Equals(sheetName));
        }

        public Sheet this[string sheetName] => Sheets.FirstOrDefault(x => x.Description == sheetName);
    }

    //TODO переделать класс листов и экшенов согласно новому тз
    /// <summary>
    /// Класс листа. Хранит в себе название, описание на русском, название процедуры, которая его вызывает, параметры
    /// </summary>
    public class Sheet
    {
        public string Description;
        public string Procedure;
        public string AccessLevel;
        public string Name;
        public List<Action> Actions = new List<Action>();
        public Action this[int index] => Actions[index];

        public Sheet(string description, string procedure, string accessLevel, string name)
        {
            Name = name;
            Description = description;
            Procedure = procedure;
            AccessLevel = accessLevel;
        }
    }
}

Elcom/Controllers/SheetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Runtime.InteropServices.ComTypes;
using System.Security.Claims;
using System.Threading.Tasks;
using Elcom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;

namespace Elcom.Controllers
{
    public class SheetsController : Controller
    {
        public ActionResult Index()
        {
            return Redirect("Home/Main");
        }
        
        public FileStreamResult DownloadXlsxFile(MemoryStream result, string name)
        {
            return new FileStreamResult(result, "application/octet-stream")
            {
                FileDownloadName = name + " " + DateTime.Now.ToString() + ".xlsx"
            };
        }
        
        public IActionResult Main()
        {
            ViewData["Title"] = "Главное меню";
            var command = new FunctionCommand("table(pkg_cmacros.getSheets)", new Param[] { new Param("accesslevel", User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value) });
            var caller = new DbCaller(command);
            caller.DoWork();
            if (((DataTable)caller.GetResult()).Rows.Count == 0)
            {
                ViewBag.Message = "Данному пользователю недоступны какие-либо действия!";
                return RedirectToAction("Login", "Home");
            }
            return View("Main", caller.GetResult());
        }

        public ActionResult XlsxOrPartial(string sheetName, int partial, Param[] parameters)
        {
            if (partial == 0)
                return Helper.GetXlsxFile(sheetName, parameters);
            else
                return PartialView("_TargetTable", Helper.GetDataTable(sheetName, parameters));

            //return Content(Convert.ToBase64String(Helper.GetBytesArray("Purchaser", sheetName, parameters)));
        }

        public ActionResult XlsxOrPartial(string sheetName, int partial, Param parameter = null)
        {
            if (partial == 0)
                return Helper.GetXlsxFile(sheetName, parameter is null ? null : new Param[] { parameter });
            else
                return PartialView("_TargetTable", Helper.GetDataTable(sheetName, parameter is null ? null : new Param[] { parameter }));
        }

        public ActionResult GetReadyFile(string name, short key)
        {
            return DownloadXlsxFile(FileHolder.GetFile(key), name);
        }
        
        public ActionResult GetDelayedIPO(int partial)
        {
            return XlsxOrPartial("GetDelayedIPO", partial);
        }

        [HttpGet]
        public ActionResult GetDelayedSO()
        {
            // Вызов осуществляется не через хелпер, так как функционал не так прост. Нужно передать извлеченную информацию в частичное представление. Сам метод работает в аяксе
            var command = new FunctionCommand(Options.Sheets["GetDelayedSO"].Procedure);
            var caller = new DbCaller(command);
            caller.DoWork();
            return PartialView("_DelayedSO", (DataTable) caller.GetResult());

            /*
            var command = new TextCommand(@"select 1 ""OrderNumber"", 1 ""LineNumber"", 1 ""DelayedDays"", 1 ""SupplementaryText5"", rf.* from dbo.""RefFoms"" rf", Returns.Table);
            var caller = new DbCaller(command, null, "PgSQL2");
            caller.DoWork();
            return PartialView("_DelayedSO", (DataTable)caller.GetResult());
            /*
            Sheet currentSheet = Purchaser.GetSheet("Задерживается ЗК");
            var command = new FunctionCommand(currentSheet.Procedure);
            var caller = new DbCaller(command);
            caller.DoWork();
            return PartialView("_DelayedSO", (DataTable)caller.GetResult());
            */
        }

        [HttpGet]
        public ActionResult FillPartialTable(string sheetName, Param[] parameters)
        {
            var command = new FunctionCommand(Options.Sheets[sheetName].Procedure);
            var caller = new DbCaller(command);
            caller.DoWork();
            return PartialView("_GetDelayedSO", (DataTable)caller.GetResult());
        }

        [HttpGet]
        public ActionResult ShowPartialForm(string viewName)
        {
            return PartialView(viewName);
        }

        [HttpGet]
        public ActionResult UpdateDelayedSO(string orderNumber, int lineNumber, string delayedDays, string supplementaryText5, int post = -1)
        {
            if (post != -1)
            {
                Random rnd = new Random();
                int value = rnd.Next(0, 10);
                return Content(value > 5 ? post.ToString() : post.ToString());
            }
            else
                return Content("Ожидание");
            
            // Обновление данных
            Param[] parameters =
            {
                new Param("fDecision", "Отправить запрос МП"), new Param("fYourRequest", "Не отправлен"), new Param("fDelayNumber", delayedDays),
                new Param("fDelay", supplementaryText5), new Param("fOrdernumb", orderNumber), new Param("fLinenumb", lineNumber)
            };
            var command = new ProcedureCommand(Options.Sheets["Обновление задерж. ЗК"].Procedure, parameters, Returns.Nothing);
            var caller = new DbCaller(command);
            try
            {
                caller.DoWork();
            }
            catch
            {
                return Content("Обновить данные не удалось!");
            }
            // Проверка, обновились ли данные. Возвращает простой текст в HTML страничку по итогам проверки
            var checkCommand = new TextCommand(string.Format("select 1 result from OrderLine where OrderNumber = {0} and LineNumber = {1} SupplementaryText5 like '%LETTER%'", orderNumber, lineNumber));
            var checkCaller = new DbCaller(checkCommand);
            try
            {
                checkCaller.DoWork();
                return Content(checkCaller.GetResult().ToString().Equals("1") ? "Успешно" : "Неуспешно");
            }
            catch (Exception e)
            {
                return Content("Проверка неуспешна");
            }
        }

        //TODO Не реализовано. Жду реализации функции от коллег
        public ActionResult GetUpdateDeliveryDates(string vendorNumbers, string dates, string numberPOs, string numberIPOs, Inventory inventory)
        {
            // Пилим список столбцов файла импорта
            List<ImportColumn> listOfColumns = new List<ImportColumn>();
            
            // Класс колонки сам распарсит строку
            // Если в строке всего один ряд, он возмет строку как значение по умолчанию
            var IPOColumn = new ImportColumn("ItemPurchaseOrderNumber", vendorNumbers);
            listOfColumns.Add(IPOColumn);
            var LinesColumn = new ImportColumn("LineNumber", "1");
            listOfColumns.Add(LinesColumn);
            var ItemsColumn = new ImportColumn("ItemNumber", "itemnumber");
            listOfColumns.Add(ItemsColumn);
            var Date2Column = new ImportColumn("Date2", dates);
            listOfColumns.Add(Date2Column);
            
            // Подгружаем из базы необходимые данные
            
            listOfColumns.Add(new ImportColumn("ExpectedCommitmentDate", numberPOs));
            listOfColumns.Add(new ImportColumn("Date1", numberIPOs));
            listOfColumns.Add(new ImportColumn("Date4", numberIPOs));
            // Создаем секцию файла импорта, передав ему название таблицы, режим и список столбцов и их значений
            var importSection = new ImportSection("ITEMPURCHASELINE", ImportMode.CreateChange, listOfColumns);
            // Создаем класс-создатель файла импорта
            var importWorker = new ImportWorker("GetUpdateDeliveryDates");
            // Передаем ему секцию и заставляем работать.
            importWorker.DoWork(importSection);
            return DownloadTxt(importWorker.GetResult(), "test");
        }

        public ActionResult GetReception(int inventory, int partial = 0)
        {
            return XlsxOrPartial("GetReception", partial, new Param("№ Склада", inventory.ToString()));
        }

        public ActionResult GetLoadPrice(int numberIPO)
        {
            var command = new FunctionCommand("table(pkg_cmacros.LoadPriceToIPO)");
            var caller = new DbCaller(command);
            caller.DoWork();
            return PartialView("_LoadPrice", (DataTable) caller.GetResult());
            //return Helper.GetXlsxFile("Purchaser", "LoadPrice", new Param("№ ЗП", numberIPO));
        }
        
        public ActionResult GetImportFileForLoadPrice(string numberIPOs, string lineNumbers, string itemNumbers, string newPrices)
        {
            List<ImportColumn> listOfColumns = new List<ImportColumn>();
            
            listOfColumns.Add(new ImportColumn("ItemPurchaseOrderNumber", numberIPOs));
            listOfColumns.Add(new ImportColumn("LineNumber", lineNumbers));
            listOfColumns.Add(new ImportColumn("ItemNumber", itemNumbers));
            listOfColumns.Add(new ImportColumn("UnitPriceCurrency", newPrices));
                
            var importSection = new ImportSection("ITEMPURCHASELINE", ImportMode.Change, listOfColumns);
            
            var worker = new ImportWorker("LoadPricesToIPO");
            
            worker.DoWork(importSection);
            return DownloadTxt(worker.GetResult(), "test");
        }

        public ActionResult GetLackOfItems(object inventory, int partial = 0)
        {
            return XlsxOrPartial("GetLackOfItems", partial, new Param("№ Склада", inventory.ToString()));
        }

        public ActionResult GetGTD(string itemNumber, int inventory, DateTime fromDate, DateTime toDate, int partial = 0)
        {

Elcom/Views/Sheets/_DelayedSO.cshtml
@using System.Data
@model DataTable;

<div class="row">
    <div class="col">
        <button type="button" class="btn btn-outline-primary btn-sm btn-block workingButton" onclick="UpdateSalesOrders();">Отправить</button>
    </div>
</div>
<table class="contentTable" style="display: block;">
    <thead>
    <tr>
        <th>Успех</th>
        <th>Отправить запрос МП</th>
        @foreach (DataColumn col in @Model.Columns)
        {
            <th>@col.ColumnName</th>
        }
    </tr>
    </thead>
    <tbody>
    @{ var i = 0; }
    @foreach (DataRow row in @Model.Rows)
    {
        <tr>
            <td>
                <div id="Complete@(i)">Ожидание</div></td>
            <td>
                @using (Html.BeginForm("UpdateDelayedSO", "Sheets", FormMethod.Post, new {@class = "UpdateSO"}))
                {
                <input type="checkbox" name="post" value="@(i)" />
                <input type="hidden" name="orderNumber" value="@row["Заказа_клиента_Но"]" />
                <input type="hidden" name="lineNumber" value="@row["Строка_Но"]" />
                <input type="hidden" name="delayedDays" value="@row["Дни_задержки_кол_во"]" />
                <input type="hidden" name="supplementaryText5" value="@row["Дни_задержки"]" />
                }
                @{ i++; }
            </td>
            @foreach (var item in row.ItemArray)
            {
                <td>@item.ToString()</td>
            }
        </tr>
    }
    </tbody>
</table>

Elcom/Views/Sheets/_GetAddToIPO.cshtml
@using (Html.BeginForm("GetAddToIPO", "Sheets", FormMethod.Get))
{
    <div class="row">
        <div class="col">
            <input type="text" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="№ поставщика" placeholder="№ Поставщика" name="vendorNumber"required>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <select class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Выберите период" name="inventory">
                <option disabled selected>Выберите период</option>
                <option value="1">1 месяц</option>
                <option value="3">3 месяца</option>
                <option value="6">6 месяцев</option>
            </select>
        </div>
    </div>
    @Html.Partial("_PartialOrExcelSubmit")
}

Elcom/Views/Sheets/_GetDelayedSO.cshtml
<div class="row">
     <div class="col">
          <button type="button" class="btn btn-outline-primary btn-sm btn-block workingButton" onclick="LoadToTargetTable('/Sheets/GetDelayedSO');">Выгрузить данные о просроченных заказах</button>
     </div>
</div>

Elcom/Views/Sheets/_GetGTD.cshtml
@using (Html.BeginForm("GetGTD", "Sheets", FormMethod.Get))
{
    <div class="row">
        <div class="col">
            <input type="text" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="№ товара" placeholder="№ товара" name="itemNumber" required>
        </div>
    </div>
    @Html.Partial("_InventoryInput")
    <div class="row">
        <div class="col">
            <input type="date" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Введите период с дд.мм.гг" placeholder="Дата" name="fromDate" required>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <input type="date" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Введите период по дд.мм.гг" placeholder="Дата" name="toDate" required>
        </div>
    </div>
    @Html.Partial("_PartialOrExcelSubmit")
}

Elcom/Views/Sheets/_GetKPIMZ.cshtml
@using (Html.BeginForm("GetKPIMZ", "Sheets", FormMethod.Get))
{
    <div class="row">
        <div class="col">
            <input type="date" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Введите период с дд.мм.гг" placeholder="Дата" name="fromDate" required>
        </div>	
    </div>
    <div class="row">
        <div class="col">
            <input type="date" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Введите период по дд.мм.гг" placeholder="Дата" name="toDate" required>
        </div>	
    </div>
    <div class="row">
        <div class="col">									
            <input type="radio" id="onlyZK" class="workingButton" data-toggle="tooltip" title="Выберите, если нужна выгрузка по КП" placeholder="Только под КП" name="orderType" value="KP">
            <label for="onlyZK"><p>Выгрузка по КП</p></label>
        </div>	
    </div>
    <div class="row">
        <div class="col">									
            <input type="radio" id="onlyZK" class="workingButton" data-toggle="tooltip" title="Выберите, если нужна выгрузка по ЗК" placeholder="Только под ЗК" name="orderType" value="SO">
            <label for="onlyKP"><p>Выгрузка по ЗК</p></label>
        </div>	
    </div>
    @Html.Partial("_PartialOrExcelSubmit")
}

Elcom/Views/Sheets/_GetLackOfItemsForSO.cshtml
@using (Html.BeginForm("GetLackOfItemsForSO", "Sheets", FormMethod.Get))
{
    @Html.Partial("_PartialOrExcelSubmit");
}

Elcom/Views/Sheets/_GetLoadPrice.cshtml
<form>
    <div class="row">
        <div class="col">
            <input type="text" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="№ ЗП" placeholder="№ ЗП" name="numberIPO" id="GetLoadPriceIPONumber" required>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <button type="button" class="btn btn-outline-primary btn-sm btn-block workingButton" onclick='$("#TargetTable").load("/Sheets/GetLoadPrice?numberIPO=" + document.getElementById("GetLoadPriceIPONumber").value);'>Выгрузить данные о строках в ЗП</button>
        </div>
    </div>
</form>

Elcom/Views/Sheets/_GetLoadPurchasePriceToQuote.cshtml
<button onclick='$("#TargetTable").load("/Sheets/ShowPartialView?sheetName=_LoadPurchasePriceToQuote");'>Выгрузить данные о просроченных заказах</button>

<div id="target"></div>

Elcom/Views/Sheets/_GetRejectedSO.cshtml
@using (Html.BeginForm("GetRejectedSO", "Sheets", FormMethod.Get))
{
    @Html.Partial("_PartialOrExcelSubmit")
}

Elcom/Views/Sheets/_GetShipmentFromVendor.cshtml
@using (Html.BeginForm("GetShipmentFromVendor", "Sheets", FormMethod.Get))
{
    <div class="row">
        <div class="col">
            <input type="text" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="№ поставщика" placeholder="№ поставщика" name="vendorNumber" required>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <input type="date" class="btn btn-outline-primary btn-sm btn-block workingButton" data-toggle="tooltip" title="Выберите дату поездки дд.мм.гг" placeholder="Дата" name="shipmentDate" required>
        </div>	
    </div>
    <div class="row">
        <div class="col">
            <label for="onlyZK"><p>Только под ЗК</p></label>
            <input type="checkbox" name="checkSO" class="workingButton" data-toggle="tooltip" title="Выберите, если нужна выгрузка только под ЗК" placeholder="Только под ЗК">
        </div>	
    </div>
    @Html.Partial("_PartialOrExcelSubmit")
}

Elcom/Views/Sheets/_GetUpdateDeliveryDates.cshtml
<div class="row">
    <div class="col">
        <button type="button" class="btn btn-outline-primary btn-sm btn-block workingButton" onclick='$("#TargetTable").load("/Sheets/ShowPartialForm?viewName=_UpdateDeliveryDates");'>Выгрузить рабочее поле</button>
    </div>
</div>

Elcom/Views/Sheets/_LoadPrice.cshtml
@using System.Data
@model DataTable;

<div>
    <button onclick="LoadPriceSubmit()">Сформировать файл импорта</button>
    <button onclick="console.log($(`#Complete0`).innerHTML);">Отправить</button>
    <table>
        <tr>
            @foreach (DataColumn col in @Model.Columns)
            {
                <td>@col.ColumnName</td>
            }
            <td>Новая цена</td>
        </tr>
        @{ var i = 0; }
        @foreach (DataRow row in @Model.Rows)
        {
            <tr>
                @foreach (var item in row.ItemArray)
                {
                    <td>@item.ToString()</td>
                }
                <td>
                    <form class="NewPricesToLoadIPO">
                        <input type="hidden" name="IPONumber" value="@row["Номер_заказа"]"/>
                        <input type="hidden" name="LineNumber" value="@row["Номер_строки"]"/>
                        <input type="hidden" name="ItemNumber" value="@row["Номер_товара"]"/>
                        <input type="text" name="NewPrice" value=""/>
                    </form>
                </td>
                @{ i++; }
            </tr>
        }
    </table>
</div>

@Html.BeginForm("GetImportFileForLoadPrice", "Sheets", FormMethod.Get, new {id="LoadPrices"}){
<input type="hidden" name="numberIPOs" id="numberIPOsLoadPrice"/>
<input type="hidden" name="lineNumbers" id="lineNumbersLoadPrice"/>
<input type="hidden" name="itemNumbers" id="itemNumbersLoadPrice"/>
<input type="hidden" name="newPrices" id="newPricesLoadPrice"/>
}

Elcom/Views/Sheets/_UpdateDeliveryDates.cshtml
@using (Html.BeginForm("GetUpdateDeliveryDates", "Sheets", FormMethod.Get))
{
<textarea id="vendorNumbers" rows="10" cols="8" name="vendorNumbers"></textarea>
<textarea id="dates" rows="10" cols="8" name="dates"></textarea>
<textarea id="numberPOs" rows="10" cols="8" name="numberPOs"></textarea>
<textarea id="numberIPOs" rows="10" cols="8" name="numberIPOs"></textarea>
<p><input type="submit" value="Выгрузить" /></p>
}
<button type="button" class="btn btn-outline-primary btn-sm btn-block workingButton" onclick="UploadFromClipboardTo(['vendorNumbers', 'dates', 'numberPOs', 'numberIPOs']);">Выгрузить из буфера обмена</button>